module Library where

-- data LibFun
--   : Fun_sin -- f -> f
--   | Fun_cos -- f -> f
--   | Fun_tan -- f -> f
--   | Fun_asin -- f -> f
--   | Fun_acos -- f -> f
--   | Fun_atan -- f -> f -> f
--   | Fun_pow -- f -> f -> f
--   | Fun_exp -- f -> f
--   | Fun_exp2 -- f -> f
--   | Fun_log -- f -> f
--   | Fun_log2 -- f -> f
--   | Fun_sqrt -- f -> f
--   | Fun_rcpsqrt -- f -> f
--   | Fun_rcp -- f -> f
--   | Fun_abs -- f -> f
--   | Fun_sign -- f -> f
--   | Fun_floor -- f -> f
--   | Fun_ceil -- f -> f
--   | Fun_round -- f -> f
--   | Fun_truncate -- f -> f
--   | Fun_fract -- f -> f
--   | Fun_mod -- f -> f -> f
--   | Fun_clamp -- f -> f -> f -> f
--   | Fun_mix -- f -> f -> f -> f
--   | Fun_step -- f -> f -> f
--   | Fun_smoothstep -- f -> f -> f -> f
--   --
--   | Fun_toInt -- f -> i
--   | Fun_toFloat -- i -> f
--   --
--   | Fun_cross -- f 3 -> f 3 -> f 3

--   deriving (Show, Eq)
